### ISSUE TITLE
Build Failure on MacOS Sonoma (14.4, Clang 18.1.8)

### ISSUE THREAD

**Issue by petridecus** [saucer/saucer#28] opened 2024-10-01 01:37 UTC
### ✍️ Bug Description

`[ 22%] Building OBJCXX object CMakeFiles/saucer.dir/cmake_pch_arm64.objcxx.hxx.pch
In file included from <built-in>:1:
In file included from /Users/apetrides/saucer/build/CMakeFiles/saucer.dir/cmake_pch_arm64.objcxx.hxx:5:
In file included from /Users/apetrides/saucer/build/_deps/jthread-src/include/jthread:7:
/Users/apetrides/saucer/build/_deps/jthread-src/include/stop_token:148:7: fatal error: reference to '__stop_callback_base' is ambiguous
  148 |       __stop_callback_base* __cb,
      |       ^
/Users/apetrides/saucer/build/_deps/jthread-src/include/stop_token:35:8: note: candidate found by name lookup is 'std::__stop_callback_base'
   35 | struct __stop_callback_base {
      |        ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/__stop_token/stop_state.h:29:8: note: candidate found by name lookup is 'std::__1::__stop_callback_base'
   29 | struct __stop_callback_base : __intrusive_node_base<__stop_callback_base> {
      |        ^
1 error generated.`

### 🔁 Steps to reproduce

Using the exact files copied over from the link below. I just made a build directory, and ran `cmake ..` followed by `make`.

https://saucer.app/docs/getting-started/basic-app

Clang 18.1.8 as mentioned, cmake version 3.26.4, GNU Make version 3.81

### 🛸 Saucer Version

3.0.0

### 🖥️ Operating System

MacOS

### 🧰 Compiler

Clang 18.1.8

### 📦 Environment

Webkit 19618.1.15.11.12

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment] 2024-10-01 05:27
This was fixed on the feat-app branch, try building that with the code of one of the samples from the example folder

**Comment by petridecus** [comment] 2024-10-01 15:33
the 'embedding' example also fails to link, seemingly due to an incompatibility with ARM architecture

`[100%] Linking CXX executable your_awesome_app
Undefined symbols for architecture arm64:
  "std::exception_ptr::__from_native_exception_pointer(void*)", referenced from:
      std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::future_error>(std::__1::future_error) in libsaucer.a[13](cocoa.window.mm.o)
  "___cxa_init_primary_exception", referenced from:
      std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::future_error>(std::__1::future_error) in libsaucer.a[13](cocoa.window.mm.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [your_awesome_app] Error 1
make[1]: *** [CMakeFiles/your_awesome_app.dir/all] Error 2
make: *** [all] Error 2
(base) apetrides@andreas-mac build %`

**Comment by Curve** [comment] 2024-10-01 16:05
> Seems like the dependencies finished building now, but that the constructor signature for smartview changed, which now breaks the example in the documentation.

That's why I advised to use a recent example from the same branch: https://github.com/saucer/saucer/blob/feat-app/examples/json-bridge/main.cpp

> also fails to link, seemingly due to an incompatibility with ARM architecture

This is a well-known issue with LLVM from brew and not an issue related to ARM or saucer, see: https://github.com/Homebrew/homebrew-core/issues/178435#issuecomment-2250615995.

You can fix this by specifying the additional compiler flags mentioned in the above post:

```sh
cmake -B build -DCMAKE_CXX_STANDARD_LIBRARIES="-L"$(brew --prefix llvm)/lib/c++" -L"$(brew --prefix llvm)/lib""
```

**I would generally not recommend using LLVM from brew unless you absolutely need to as it's a pain to work with, especially due to issues as seen here.**

Out of curiosity, why do you insist on using LLVM from brew? Does the xcode provided clang lack something you desperately need?

**Comment by petridecus** [comment] 2024-10-01 19:24
Pointing it at xcode's version of clang got both examples to work! 

I have a more recent version of clang installed to future proof older apps. Clang can be a lot more harsh on older syntax than other compilers. Come to think of it though it's possible I've only cross-compiled for x86 using clang 18, which would explain why I haven't encountered this type of issue before.

**Comment by Curve** [comment] 2024-10-01 19:31
> Pointing it at xcode's version of clang got both examples to work! 
> 
> I have a more recent version of clang installed to future proof older apps. Clang can be a lot more harsh on older syntax than other compilers. Come to think of it though it's possible I've only cross-compiled for x86 using clang 18, which would explain why I haven't encountered this type of issue before.

The issue is caused by the xcode clang being significantly behind clang 18 and thus the required symbols mismatch, which is going to be an issue for every architecture :)

With the above flags you can properly compile it on clang 18 as well, but as we've seen there's often a lot of manual tinkering required :D

I'll close this as the issue is fixed, the latest changes will be merged in the next couple days :)

**Closed by Curve** 2024-10-01 19:31 UTC
Labels: bug
